version: "3.9"

services:
  jenkins:
    image: ajoel24/jenkins:latest
    hostname: jenkins
    ports:
      - "9000:8080"
      - "50000:50000"
    environment:
      JENKINS_ADMIN_ID: "admin"
      JENKINS_ADMIN_PASSWORD: "admin"
      VIRTUAL_HOST: jenkins.local
      VIRTUAL_PORT: 8080
    volumes:
      - jenkins-volume:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local-network

  sonarqube:
    image: sonarqube:9.9.0-community
    hostname: sonarqube
    ports:
      - "9001:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data/
      - sonarqube-extensions:/opt/sonarqube/extensions/
      - sonarqube-logs:/opt/sonarqube/logs/
    environment:
      VIRTUAL_HOST: sonarqube.local
      VIRTUAL_PORT: 9000
    networks:
      - local-network

volumes:
  jenkins-volume:
  jenkins-docker-certs:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:

networks:
  local-network:
    external: true
