version: "3.7"

services:
  jenkins-dind:
    image: docker:dind
    hostname: jenkins-dind
    container_name: jenkins-dind
    privileged: true
    ports:
      - "3000:3000"
      - "5000:5000"
      - "2376:2376"
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-volume:/var/jenkins_home

  jenkins:
    image: ajoel24/jenkins:latest
    hostname: jenkins
    container_name: jenkins
    restart: on-failure
    depends_on:
      - jenkins-dind
    ports:
      - "9000:8080"
      - "50000:50000"
    environment:
      JENKINS_ADMIN_ID: "admin"
      JENKINS_ADMIN_PASSWORD: "admin"
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-volume:/var/jenkins_home/
      - jenkins-docker-certs:/certs/client:ro

  sonarqube:
    image: sonarqube:9.9.0-community
    depends_on:
      - jenkins
    hostname: sonarqube
    container_name: sonarqube
    ports:
      - "9001:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data/
      - sonarqube-extensions:/opt/sonarqube/extensions/
      - sonarqube-logs:/opt/sonarqube/logs/

volumes:
  jenkins-volume:
  jenkins-docker-certs:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:
