version: "3.7"

services:
  jenkins:
    image: ajoel24/jenkins:latest
    hostname: jenkins
    restart: on-failure
    ports:
      - "9000:8080"
      - "50000:50000"
    environment:
      JENKINS_ADMIN_ID: "admin"
      JENKINS_ADMIN_PASSWORD: "admin"
      VIRTUAL_HOST: jenkins.local
      VIRTUAL_PORT: 8080
    volumes:
      - jenkins-volume:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock

  sonarqube:
    image: sonarqube:9.9.0-community
    hostname: sonarqube
    restart: on-failure
    ports:
      - "9001:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data/
      - sonarqube-extensions:/opt/sonarqube/extensions/
      - sonarqube-logs:/opt/sonarqube/logs/
    environment:
      VIRTUAL_HOST: sonarqube.local
      VIRTUAL_PORT: 9000

  nginx:
    image: jwilder/nginx-proxy
    hostname: nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  jenkins-volume:
  jenkins-docker-certs:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:
