version: "3.7"

services:
  jenkins:
    image: ajoel24/jenkins:latest
    hostname: jenkins
    container_name: jenkins
    restart: on-failure
    ports:
      - "9000:8080"
      - "50000:50000"
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      JENKINS_ADMIN_ID: "admin"
      JENKINS_ADMIN_PASSWORD: "admin"
    volumes:
      - /var/lib/docker.sock:/var/lib/docker.sock
      - jenkins-volume:/var/jenkins_home/

  sonarqube:
    image: sonarqube:9.9.0-community
    depends_on:
      - jenkins
    hostname: sonarqube
    container_name: sonarqube
    ports:
      - "9001:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data/
      - sonarqube-extensions:/opt/sonarqube/extensions/
      - sonarqube-logs:/opt/sonarqube/logs/

volumes:
  jenkins-volume:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:
