version: "3.7"

services:
  jenkins:
    image: ajoel24/jenkins:latest
    hostname: jenkins
    container_name: jenkins
    restart: on-failure
    ports:
      - "9000:8080"
      - "50000:50000"
    environment:
      JENKINS_ADMIN_ID: "admin"
      JENKINS_ADMIN_PASSWORD: "admin"
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - "jenkins-volume:/var/jenkins_home/"
      - "jenkins-docker-certs:/certs/client:ro"

volumes:
  jenkins-volume:
  jenkins-docker-certs:
