version: "3.9"

services:
  nginx:
    image: jwilder/nginx-proxy
    hostname: nginx
    deploy:
      replicas: 2
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - local-network

networks:
  local-network:
    external: true
